apiVersion: v1
kind: Pod
metadata:
  name: phaedra
  labels:
    ci: phaedra-build
spec:
  volumes:
    - name: maven-repo
      emptyDir: {}
  containers:
   - name: phaedra-build
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/phaedra-build
     securityContext:
      privileged: true  
     tty: true
